In [8]:
import numpy as np

# Dimensões da tela
screen_width = 1920
screen_height = 1080

# Dimensões do grid
grid_cols = 10
grid_rows = 6

# Tamanho de cada célula
cell_width = screen_width // grid_cols
cell_height = screen_height // grid_rows

# Função para quantizar coordenadas (x, y) para o grid
def quantize_to_grid(x, y):
    col = min(x // cell_width, grid_cols - 1)
    row = min(y // cell_height, grid_rows - 1)
    return (col, row)

# Exemplo de uso
x, y = 288, 179  # Exemplo de coordenada
col, row = quantize_to_grid(x, y)
print(f"Coordenada ({x}, {y}) está no grid: col={col}, row={row}")

# Opcional: criar uma matriz para representar o grid
grid = np.zeros((grid_rows, grid_cols), dtype=int)

# Marcar a célula onde o ponto está
grid[row, col] = 1

print("\nGrid representado como matriz (6 linhas x 10 colunas):")
print(grid)

Coordenada (288, 179) está no grid: col=1, row=0

Grid representado como matriz (6 linhas x 10 colunas):
[[0 1 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]]


In [9]:
def get_grid_center(x, y):
    col = min(x // cell_width, grid_cols - 1)
    row = min(y // cell_height, grid_rows - 1)
    
    # Calcula o centro da célula
    x_center = (col * cell_width) + (cell_width // 2)
    y_center = (row * cell_height) + (cell_height // 2)
    
    return (x_center, y_center)

# Exemplo de uso
x, y = 500, 300  # Coordenada de exemplo
x_center, y_center = get_grid_center(x, y)

print(f"Coordenada ({x}, {y}) está na célula com centro em: ({x_center}, {y_center})")

Coordenada (500, 300) está na célula com centro em: (480, 270)


In [22]:
# Dados originais
pitch_min = 0.14
pitch_max = 0.5
input_pitch = 0.14

# 1. Calcula o offset para deslocar o mínimo para 0
pitch_offset = -pitch_min  # pitch_offset = 0.14

# 2. Escalona o valor de entrada
escalonado = input_pitch + pitch_offset  # 0.27 + 0.14 = 0.41

# 3. Calcula o novo máximo escalonado
pitch_max_escalonado = pitch_max + pitch_offset  # 0.27 + 0.14 = 0.41

# 4. Calcula a porcentagem no range escalonado (0 a pitch_max_escalonado)
porcentagem = (escalonado / pitch_max_escalonado) * 100  # (0.41 / 0.41) * 100 = 100%

print("Valor escalonado:", escalonado)  # Saída: 0.41
print("Porcentagem:", porcentagem, "%")  # Saída: 100.0 %

Valor escalonado: 0.0
Porcentagem: 0.0 %


In [2]:
# Dados originais (ambos positivos)
pitch_min = -0.24
pitch_max = 0.5
input_pitch = 0.49

# 1. Calcula o offset para deslocar o mínimo para 0
pitch_offset = -pitch_min  # -0.14

# 2. Escalona o valor de entrada
escalonado = input_pitch + pitch_offset  # 0.14 + (-0.14) = 0.0

# 3. Calcula o novo máximo escalonado
pitch_max_escalonado = pitch_max + pitch_offset  # 0.5 + (-0.14) = 0.36

# 4. Calcula a porcentagem no range escalonado (0 a pitch_max_escalonado)
porcentagem = (escalonado / pitch_max_escalonado) * 1920  # (0.0 / 0.36) * 100 = 0.0%

print("Valor escalonado:", escalonado)  # Saída: 0.0
print("Porcentagem:", porcentagem)  # Saída: 0.0%

Valor escalonado: 0.73
Porcentagem: 1894.0540540540542


In [ ]:
import csv
def load_and_convert_csv(file_path):
    data = []
    with open(file_path, newline='') as f:
        reader = csv.reader(f)
        for row in reader:
            # Converte cada valor na linha para float
            try:
                converted_row = [float(value) for value in row]
                data.append(converted_row)
            except ValueError as e:
                print(f"Aviso: Não foi possível converter a linha {row}: {e}")
                continue
    return np.array(data)

file_path = 'calib_10xPonto/calib12/calib_file12_5pontos.csv'
data = load_and_convert_csv(file_path)

[[-4.2912440e-01 -2.8342914e-03  5.0000000e+01  5.0000000e+01]
 [ 1.6559495e-01 -1.4220923e-01  1.8700000e+03  5.0000000e+01]
 [-1.9365984e-01 -3.0669720e-01  9.6000000e+02  5.4000000e+02]
 [-5.2885540e-01 -3.7399860e-01  5.0000000e+01  1.0300000e+03]
 [ 2.4031176e-01 -4.2906272e-01  1.8700000e+03  1.0300000e+03]]


In [68]:
firstQ = data[0]
secondQ = data[1]
center = data[2]
thirdQ = data[3]
forthQ = data[4]
print(center)

[-1.9365984e-01 -3.0669720e-01  9.6000000e+02  5.4000000e+02]


In [ ]:
p, y = 0.24, -.429
width, height = 1920/2, 1080/2

if p < center[0]:
    #primeiro quadrante
    if y > center[1]:
        pitch_offset = -firstQ[0] 
        pitch_escalonado = p + pitch_offset
        pitch_max_escalonado = center[0] + pitch_offset
        pos_x = (pitch_escalonado / pitch_max_escalonado) * width

        yaw_offset = -firstQ[1]
        yaw_escalonado = y + yaw_offset
        yaw_max_escalonado = center[1] + yaw_offset
        pos_y = (yaw_escalonado / yaw_max_escalonado) * height

    #terceiro quadrante
    elif y < center[1]:
        pitch_offset = -thirdQ[0] 
        pitch_escalonado = p + pitch_offset
        pitch_max_escalonado = center[0] + pitch_offset
        pos_x = (pitch_escalonado / pitch_max_escalonado) * width

        yaw_offset = -center[1]
        yaw_escalonado = y + yaw_offset
        yaw_max_escalonado = thirdQ[1] + yaw_offset
        pos_y = (yaw_escalonado / yaw_max_escalonado) * height + 540

if p > center[0]:
    #segundo quadrante
    if y > center[1]:
        pitch_offset = -center[0]
        pitch_escalonado = p + pitch_offset
        pitch_max_escalonado = secondQ[0] + pitch_offset
        pos_x = (pitch_escalonado / pitch_max_escalonado) * width + 960

        yaw_offset = -secondQ[1]
        yaw_escalonado = y + yaw_offset
        yaw_max_escalonado = center[1] + yaw_offset
        pos_y = (yaw_escalonado / yaw_max_escalonado) * height

    #quarto quadrante
    elif y < center[1]:
        pitch_offset = -center[0] 
        pitch_escalonado = p + pitch_offset
        pitch_max_escalonado = forthQ[0] + pitch_offset
        pos_x = (pitch_escalonado / pitch_max_escalonado) * width + 960

        yaw_offset = -center[1]
        yaw_escalonado = y + yaw_offset
        yaw_max_escalonado = forthQ[1] + yaw_offset
        pos_y = (yaw_escalonado / yaw_max_escalonado) * height + 540


print(pos_x)
print(pos_y)

1919.3103474973939
1079.7232161478169


In [8]:
import numpy as np
import csv
def load_and_convert_csv(file_path):
    data = []
    with open(file_path, newline='') as f:
        reader = csv.reader(f)
        for row in reader:
            # Converte cada valor na linha para float
            try:
                converted_row = [float(value) for value in row]
                data.append(converted_row)
            except ValueError as e:
                print(f"Aviso: Não foi possível converter a linha {row}: {e}")
                continue
    return np.array(data)

In [ ]:
file_path = 'calib_10xPonto/calib12/calib_file12_pt2.csv'
data = load_and_convert_csv(file_path)

In [14]:
pitch_min = np.mean( (data[0][0], data[2][0]))
pitch_min

np.float64(-0.501268325)